$(function(){
  var mappings = [
{ value: 'action', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d09735' },
{ value: 'activation', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d09741' },
{ value: 'adaptation', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d09758' },
{ value: 'anticipation', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d09849' },
{ value: 'arousal', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d09883' },
{ value: 'association', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d098bd' },
{ value: 'attention', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d09902' },
{ value: 'awareness', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d09b4b' },
{ value: 'belief', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d09b85' },
{ value: 'categorization', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d09c28' },
{ value: 'choice', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d09c8c' },
{ value: 'cognition', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d09d29' },
{ value: 'communication', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d09d9e' },
{ value: 'competition', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d09daa' },
{ value: 'concept', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d09db6' },
{ value: 'consciousness', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d09e35' },
{ value: 'context', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d09e6f' },
{ value: 'coordination', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d09f07' },
{ value: 'distraction', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d0a0f3' },
{ value: 'efficiency', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d0a145' },
{ value: 'effort', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d0a151' },
{ value: 'emotion', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d0a17f' },
{ value: 'expertise', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d0a25e' },
{ value: 'feedback', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d0a33b' },
{ value: 'fixation', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d0a35e' },
{ value: 'focus', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d0a381' },
{ value: 'gaze', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d0a3d2' },
{ value: 'goal', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d0a419' },
{ value: 'imagery', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d0a510' },
{ value: 'induction', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d0a579' },
{ value: 'inference', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d0a5ed' },
{ value: 'inhibition', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d0a613' },
{ value: 'insight', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d0a62b' },
{ value: 'integration', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d0a65a' },
{ value: 'intelligence', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d0a666' },
{ value: 'intention', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d0a67d' },
{ value: 'interference', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d0a6ad' },
{ value: 'judgment', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d0a723' },
{ value: 'knowledge', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d0a746' },
{ value: 'language', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d0a769' },
{ value: 'learning', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d0a7bb' },
{ value: 'listening', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d0a803' },
{ value: 'meaning', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d0a86e' },
{ value: 'memory', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d0a891' },
{ value: 'monitoring', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d0a94f' },
{ value: 'mood', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d0a95a' },
{ value: 'movement', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d0a9c4' },
{ value: 'naming', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d0a9dc' },
{ value: 'navigation', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d0aa00' },
{ value: 'perception', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d0ab7c' },
{ value: 'planning', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d0acc1' },
{ value: 'reading', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d0aeb6' },
{ value: 'reasoning', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d0aec1' },
{ value: 'retention', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d0af7d' },
{ value: 'retrieval', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d0af94' },
{ value: 'rhythm', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d0afc3' },
{ value: 'risk', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d0afcf' },
{ value: 'rule', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d0aff2' },
{ value: 'salience', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d0b020' },
{ value: 'search', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d0b037' },
{ value: 'skill', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d0b11a' },
{ value: 'strategy', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d0b29c' },
{ value: 'stress', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d0b2a8' },
{ value: 'uncertainty', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d0b3fa' },
{ value: 'utility', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d0b412' },
{ value: 'valence', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d0b429' },
{ value: 'decision', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d0b61f' },
{ value: 'empathy', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d0b67d' },
{ value: 'fear', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d0b689' },
{ value: 'comprehension', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d0b6b9' },
{ value: 'morphology', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d0b83e' },
{ value: 'consolidation', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d0b8cd' },
{ value: 'encoding', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d0b8e5' },
{ value: 'familiarity', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d0b8fc' },
{ value: 'recall', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d0b95b' },
{ value: 'recognition', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d0b967' },
{ value: 'remembering', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d0b97e' },
{ value: 'maintenance', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d0ba30' },
{ value: 'manipulation', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d0ba3c' },
{ value: 'rehearsal', atlas: 'http://cognitiveatlas.org/id/trm_4a3fd79d0ba54' },
{ value: 'reward', atlas: 'http://cognitiveatlas.org/id/trm_4b6525253c63f' },
{ value: 'pain', atlas: 'http://cognitiveatlas.org/id/trm_4b65259eeee34' },
{ value: 'updating', atlas: 'http://cognitiveatlas.org/id/trm_4c3e05903e4bb' },
{ value: 'thought', atlas: 'http://cognitiveatlas.org/id/trm_4fa295124a375' },
{ value: 'multisensory', atlas: 'http://cognitiveatlas.org/id/trm_4e31d3ba7d25b' },
{ value: 'priming', atlas: 'http://cognitiveatlas.org/id/trm_4e89aebaa311d' },
{ value: 'expectancy', atlas: 'http://cognitiveatlas.org/id/trm_4ebfe9a465449' },
{ value: 'addiction', atlas: 'http://cognitiveatlas.org/id/trm_4fafd1626bf2b' },
{ value: 'impulsivity', atlas: 'http://cognitiveatlas.org/id/trm_50070dce14554' },
{ value: 'anxiety', atlas: 'http://cognitiveatlas.org/id/trm_5022ef7599294' },
{ value: 'Strength', atlas: 'http://cognitiveatlas.org/id/trm_50eb5469ba37a' },
{ value: 'Balance', atlas: 'http://cognitiveatlas.org/id/trm_50eb56a7867db' },
{ value: 'sleep', atlas: 'http://cognitiveatlas.org/id/trm_5159c70d0e98e' },
{ value: 'loss', atlas: 'http://cognitiveatlas.org/id/trm_5159c80c1dd24' },
{ value: 'hyperactivity', atlas: 'http://cognitiveatlas.org/id/trm_523c7c13bc55f' },
{ value: 'psychosis', atlas: 'http://cognitiveatlas.org/id/trm_52405de6b7a63' },
{ value: 'eating', atlas: 'http://cognitiveatlas.org/id/trm_525d8b8908809' },
  ];
// setup autocomplete function pulling from mappings[] array
$('#autocomplete').autocomplete({
lookup: mappings,
onSelect: function (term) {
var thehtml = '<strong>Term Name:</strong> ' + term.value + '<br><br><div id="column"><p>Go <a href="http://neurosynth.org/features/' + term.value + '/" target="_blank">to Neurosynth page</a></p></div><div id="column"><p>Go <a href="' + term.atlas +'" target="_blank">to Cognitive Atlas page</a></p></div>';
$('#outputcontent').html(thehtml);
}
});
});